In [6]:
import numpy as np
import numpy.linalg as LA
from numpy import sqrt

### Task 1

In [2]:
A = np.array([[2, -3], [-1, 2]])
B = np.array([[2, -1], [4, -2]])
T = np.array([[2, -1], [-1, -2]])

In [5]:
LA.inv(T) @ B @ LA.inv(A) @ T

array([[ 0.,  0.],
       [-2., 11.]])

In [12]:
del A, B, T

### Task 2

In [7]:
A = np.array([[2, 1, 2], [-2, -1, -2], [4, 2, 4], [2, 1, 2]])

U = np.array([[1/sqrt(7), 1/sqrt(2), -1/sqrt(3), -1/sqrt(42)],
              [-1/sqrt(7), 1/sqrt(2), 1/sqrt(3), 1/sqrt(42)],
              [2/sqrt(7), 0, 1/sqrt(3), -sqrt(2/21)],
              [1/sqrt(7), 0, 0, sqrt(6/7)]])

S = np.array([[sqrt(63), 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]])

V = np.array([[-2/3, sqrt(2)/6, 1/sqrt(2)],
              [-1/3, -sqrt(8)/3, 0],
              [-2/3, sqrt(2)/6, -1/sqrt(2)]]) * (-1)

In [10]:
np.allclose(A, U @ S @ V.T)

True

In [11]:
U @ S @ V.T

array([[ 2.,  1.,  2.],
       [-2., -1., -2.],
       [ 4.,  2.,  4.],
       [ 2.,  1.,  2.]])

In [13]:
del A, U, S, V

### Task 3

In [ ]:
A = np.array([[0, 0, 1, 1],
              [0, 1, 0, 1],
              [1, 0, 0, 0],
              [1, 0, 1, 1]])

# Markov transition matrix from row i to col j
P = np.array([[0, 0, 1/2, 1/2],
             [0, 1/2, 0, 1/2],
             [1, 0, 0, 0],
             [1/3, 0, 1/3, 1/3]])
P = P.T

In [59]:
P = 0.85 * P + 0.15 * 1 / A.shape[0] * np.ones(A.shape)

In [60]:
P

array([[0.0375    , 0.0375    , 0.8875    , 0.32083333],
       [0.0375    , 0.4625    , 0.0375    , 0.0375    ],
       [0.4625    , 0.0375    , 0.0375    , 0.32083333],
       [0.4625    , 0.4625    , 0.0375    , 0.32083333]])

In [61]:
v, w = LA.eig(P)
print(v.round(2))
print(np.abs(w.round(2)))

[ 1.   -0.57  0.43 -0.  ]
[[0.65 0.82 0.57 0.53]
 [0.12 0.   0.67 0.  ]
 [0.5  0.41 0.38 0.27]
 [0.55 0.41 0.29 0.8 ]]


In [62]:
# using iterative method
res = P @ np.array([0.25, 0.25, 0.25, 0.25])
for _ in range(1000):
    res = P @ res

res

array([0.35703631, 0.06521739, 0.27501445, 0.30273185])

In [65]:
del A, P, v, w, res

### Task 4

In [72]:
# Markov transition matrix
A = np.array([[0.73, 0.12, 0.1], 
              [0.15, 0.73, 0.2], 
              [0.12, 0.15, 0.7]])

In [73]:
v, w = LA.eig(A)
print(v.round(2))
print(w.round(2))

[1.   0.62 0.54]
[[ 0.5   0.81  0.18]
 [ 0.68 -0.46 -0.78]
 [ 0.54 -0.36  0.6 ]]


In [85]:
C = w  # matrix of eigenvectors

B = np.array([[9400], [500], [100]])

In [86]:
c = LA.inv(C) @ B
c

array([[5824.05384286],
       [8028.80416915],
       [-307.16520015]])

In [88]:
u_t = c[0] * w.T[0]
u_t.round(0)

array([2916., 3945., 3139.])

In [89]:
sum(u_t.round())

10000.0

In [83]:
2916 + 3945+ 3139

10000